### PR TITLE
update pendulum == 3.0

### LINKED ISSUE #292: Dependency issues with pendulum and python 3.12
flask-praetorian requires package pendulum `^2.1`.
Pendulum <3.0.0 requires package distutils. Package distutils is no longer available on python 3.12.
Package pendulum removed the dependency to distutils starting with version 3.0.0 (Ref: [Pendulum issues 696](https://github.com/sdispater/pendulum/issues/696)).

To be able to use flask-praetorian with python 3.12 and later, I assume flask-praetorian has to support pendulum >= 3.0.0.

```
>> pip install --upgrade flask-praetorian==1.5.0 pendulum==3.0.0
[...]
Collecting pendulum==3.0.0
  Using cached pendulum-3.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
[...]
INFO: pip is looking at multiple versions of flask-praetorian to determine which version is compatible with other requirements. This could take a while.
Collecting flask-praetorian==1.5.0
  Using cached flask_praetorian-1.5.0-py3-none-any.whl.metadata (4.0 kB)
ERROR: Cannot install flask-praetorian==1.5.0 and pendulum==3.0.0 because these package versions have conflicting dependencies.

```

### PR DESCRIPTION
**Pull request by azliu0**
Resolves #292. Updated dependencies to support pendulum >= 3.0 so that the package is compatible with Python 3.12. All tests pass.

### CODE REVIEW

**Comment by dusktreader** [comment]
When I install flask-praetorian with the updated dependencies and python 3.12 in a docker container, I'm getting compatibility issues with flask-mail:

```flask-praetorian-tutorial-dev-api-1  |   ChefBuildError
flask-praetorian-tutorial-dev-api-1  |
flask-praetorian-tutorial-dev-api-1  |   Backend 'setuptools.build_meta:__legacy__' is not available.
flask-praetorian-tutorial-dev-api-1  |
flask-praetorian-tutorial-dev-api-1  |   Traceback (most recent call last):
flask-praetorian-tutorial-dev-api-1  |     File "/usr/local/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
flask-praetorian-tutorial-dev-api-1  |       obj = import_module(mod_path)
flask-praetorian-tutorial-dev-api-1  |             ^^^^^^^^^^^^^^^^^^^^^^^
flask-praetorian-tutorial-dev-api-1  |     File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
flask-praetorian-tutorial-dev-api-1  |       return _bootstrap._gcd_import(name[level:], package, level)
flask-praetorian-tutorial-dev-api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap_external>", line 995, in exec_module
flask-praetorian-tutorial-dev-api-1  |     File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
flask-praetorian-tutorial-dev-api-1  |     File "/tmp/tmpwyl3p68n/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 8, in <module>
flask-praetorian-tutorial-dev-api-1  |       import distutils.core
flask-praetorian-tutorial-dev-api-1  |   ModuleNotFoundError: No module named 'distutils'
flask-praetorian-tutorial-dev-api-1  |
flask-praetorian-tutorial-dev-api-1  |
flask-praetorian-tutorial-dev-api-1  |   at /usr/local/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
flask-praetorian-tutorial-dev-api-1  |       160│
flask-praetorian-tutorial-dev-api-1  |       161│                 error = ChefBuildError("\n\n".join(message_parts))
flask-praetorian-tutorial-dev-api-1  |       162│
flask-praetorian-tutorial-dev-api-1  |       163│             if error is not None:
flask-praetorian-tutorial-dev-api-1  |     → 164│                 raise error from None
flask-praetorian-tutorial-dev-api-1  |       165│
flask-praetorian-tutorial-dev-api-1  |       166│             return path
flask-praetorian-tutorial-dev-api-1  |       167│
flask-praetorian-tutorial-dev-api-1  |       168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
flask-praetorian-tutorial-dev-api-1  |
flask-praetorian-tutorial-dev-api-1  | Note: This error originates from the build backend, and is likely not a problem with poetry but with flask-mail (0.9.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "flask-mail (==0.9.1)"'.
```

I may explore changing to depend on flask-mailgun instead.

**Comment by azliu0** [comment]
How can I reproduce this error? On my end, it seems like the latest version of flask-mail (0.9.1) and flask-praetorian (with pendulum==3.0) work fine together. 

When I run the `flask-praetorian-tutorial-api` container with flask-praetorian updated dependencies, I have to make two changes to `api/src/pyproject.toml`: 
- `flask-sqlalchemy = "^3.1.1"`
- `pendulum = "^3.0"`

The first change seems unrelated to upgrading pendulum. After making these changes, I'm able to run the container fine.

**Comment by dusktreader** [comment]
> How can I reproduce this error? On my end, it seems like the latest version of flask-mail (0.9.1) and flask-praetorian (with pendulum==3.0) work fine together.
> 
> When I run the `flask-praetorian-tutorial-api` container with flask-praetorian updated dependencies, I have to make two changes to `api/src/pyproject.toml`:
> 
> * `flask-sqlalchemy = "^3.1.1"`
> * `pendulum = "^3.0"`
> 
> The first change seems unrelated to upgrading pendulum. After making these changes, I'm able to run the container fine.

Did you change the base image for the flask-praetorian-tutorial/api's image? I get this error when I switch it to `python:3.12-bookworm`.

**Comment by dusktreader** [comment]
Addressed the issues encountered here with the flask-mail dependency in #296

**Comment by azliu0** [comment]
I'm not sure what's going on with the flask-mail dependency? When I use `python:3.12-bookworm`, I'm still able to run the container fine (including making curl requests etc.) Here is my `pyproject.toml`:
```
[tool.poetry]
name = "flask-praetorian-tutorial"
version = "0.1.0"
description = ""
authors = ["Tucker Beck <tucker.beck@officeally.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask-cors = "^3.0"
flask-sqlalchemy = "^3.1"
pendulum = "^3.0"
flask-praetorian = {git = "https://github.com/azliu0/flask-praetorian"}
[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by dusktreader** [comment]
@azliu0 
Support for Python 3.12 has been published in flask-praetorian v1.6.0 on PyPI.

**Comment by azliu0** [comment]
great, thank you so much!

**Pull request closed without merging**
