### PR TITLE
dusktreader/flask-praetorian#172 Added `auth_accepted` decorator, to …

### PR DESCRIPTION
**Pull request by pahrohfit**
Added an `auth_accepted` decorator.

When used, the presence of a valid token will be processed, and the `current_user()` details will be present. When not provided, no processing is done, and no errors are produced.

```
     @app.route('/kinda_protected')
     @flask_praetorian.auth_accepted
     def kinda_protected():
         try:
             authed_user = flask_praetorian.current_user().username
         except Exception as e:  # noqa: F841
             authed_user = None
         return jsonify(message='success', user=authed_user)
```

### CODE REVIEW

**Review by dusktreader — CHANGES_REQUESTED** [review]
Added a couple of comments for you below. Thanks for the contribution!

**Comment by dusktreader** [comment]
rebased branch on origin/master and applied fixes based on the code review. Will be merged in the other pull request.

Thanks for contributing!

**Comment by RylanSchaeffer** [comment]
@dusktreader what's the right way to use `auth_accepted`? I can't find an example in the tutorial or documentation. Would you recommend the try catch?

**Comment by RylanSchaeffer** [comment]
@dusktreader can I nudge you for an example? Thanks in advance!

**Comment by dusktreader** [comment]
@RylanSchaeffer Sorry I didn't notice this for a while.

The `@auth_accepted` decorator can be used for endpoints where you _might_ want to get user data. For example, maybe your app supports anonymous access on some endpoints but wants to note when a specific user is doing something. `@auth_accepted` will set the current user _if_ one is logged in. Otherwise, it will leave the current user as null and not throw a 401 if there is no token.

**Pull request closed without merging**
