### PR TITLE
Issue #250: allow flask 2.0, bump to version 1.2.1

### LINKED ISSUE #250: Flask 2.0 Support
Hello, Flask 2.0 was recently released however I'm unable to upgrade my application due to praetorian requiring flask <2.0: https://github.com/dusktreader/flask-praetorian/blob/master/poetry.lock#L196

I'm not familiar with Poetry - but it seems like it's `flask-buzz` that has the <2.0 requirement for flask?

If you can help confirm whether a change needs to be made to buzz and/or praetorian then I'm happy to help from there.

Thanks!

### PR DESCRIPTION
**Pull request by jvllmr**
pytest didn't have any complaints and I didn't face any complications when testing it with my project. I suggest to just update the dependencies.

fixes #250

### CODE REVIEW

**Review by dsposito-ubtech — APPROVED** [review]

**Review by dusktreader — APPROVED** [review]

**Comment by dsposito-ubtech** [comment]
@dusktreader @kreyoo I'm still having trouble getting flask-praetorian to work properly with Flask 2.0

I think we still need to publish the merged updates to PyPI? It's showing `v1.2.0` there but should be `v1.2.1`: https://pypi.org/project/flask-praetorian/

**Comment by jvllmr** [comment]
> @dusktreader @kreyoo I'm still having trouble getting flask-praetorian to work properly with Flask 2.0
> 
> I think we still need to publish the merged updates to PyPI? It's showing `v1.2.0` there but should be `v1.2.1`: https://pypi.org/project/flask-praetorian/

You're right, the changes aren't published yet.
For now you have to add flask-praetorian via a git dep if you want to use them:

https://pip.pypa.io/en/stable/topics/vcs-support/

https://python-poetry.org/docs/dependency-specification/#git-dependencies

**Comment by dsposito-ubtech** [comment]
@kreyoo Thanks for the workaround - I got it working. :+1: 

Any thoughts on when these latest changes will be published to pypi? Any reason not to do so now / soonish?

While the workaround works, it's not ideal because my app's docker image is now 90MB larger due to needing `git` to be installed for the VCS workaround.

@dusktreader

**Comment by dusktreader** [comment]
@dsposito-ubtech I've been reluctant to publish right now because I wanted to get some integration tests set up for flask-praetorian for some time.

I think I will publish as-is and target integration tests for the next major version of flask-praetorian (whenever that will be =] )

**Comment by dusktreader** [comment]
@dsposito-ubtech @kreyoo version 1.3.0 has been released.

**Comment by dsposito-ubtech** [comment]
Appreciate it - thanks everyone! :rocket:

**Pull request merged**
